#!/res/busybox sh

export PATH=/res/asset:$PATH

SWAPSIZE=1536
PRIORITY=10

if cat /proc/swaps | grep -q vnswap0 ; then
	echo "vnswap is already enabled!"
	exit 1
fi
echo $(($SWAPSIZE * 1048576)) > /sys/block/vnswap0/disksize
mkswap /dev/block/vnswap0
swapon -p $PRIORITY /dev/block/vnswap0
